### PR TITLE
Fix $clone width

### PR DESCRIPTION
**Pull request by EmanH**
Set correct $clone width to $textarea width rather than css value

### CODE REVIEW

**Comment by flaviusmatis** [comment]
Can you please give a better explanation for this? I don't really understand why is it necessary.

**Comment by EmanH** [comment]
Yeah. So suppose my text area has the css style width of `width: 95%`, but it's nested deep within my HTML template and and constrained to a width of 300px by its parent element.

Your will create a $clone, append that to the body and set the width to 95%. That however, is 95% of the width of the body, not 95% the width of the text area's parent element. 

This PR fixes that issue by setting the clone to the calculated width of the textarea. Hope that makes sense.

**Comment by flaviusmatis** [comment]
I get it now, but that is not a correct assumption. The actual width of the textarea is copied to the clone anyway, regardless of how that width is set (percents or fix width). There's even a resize event that will update the width of the clone in case the browser window is resized and the variable width of the original textarea changes.

So if you've found a bug here, please let me know how to reproduce it and i'll try to fix it. Setting the width like that doesn't look like a solution to me.

Thanks,
Flavius

**Comment by EmanH** [comment]
Mmm... ok. Well I was having that problem, and that fixed it for me. Nevermind then.

**Comment by flaviusmatis** [comment]
So i've just updated the plugin, the width of the clone is now recalculated every time the content is updated. This should fix your problem as well.

**Comment by EmanH** [comment]
No worries

**Pull request closed without merging**
